-- ============================================================================
--  ALAS · Inventario — Apartado "Calendario de inventarios"
--  Correr en el SQL Editor del proyecto Supabase del módulo Inventario
--  (mismo proyecto de Usos internos: ztzmhkjvfoutoprtttha).
--
--  Patrón: RLS abierta a anon (la seguridad real es el SSO ALAS en la UI).
--  La anon key es pública por diseño. NUNCA usar service_role en el cliente.
--
--  Estados: 'programado' · 'en_proceso' · 'realizado' · 'pendiente'
--  Las mercaderías del buscador siguen viniendo del archivo JS (mercaderias-data.js);
--  acá guardamos por ítem el snapshot (codigo/descripcion) + el conteo.
-- ============================================================================

-- ── Inventarios programados ────────────────────────────────────────────────
create table if not exists inventarios (
  id           bigint generated by default as identity primary key,
  fecha        date not null,
  hora         time,
  deposito     text,
  sector       text,
  marca        text,                 -- marca / familia elegida
  prioridad    text not null default 'NORMAL',
  responsable  text,
  ubicacion    text,
  estado       text not null default 'programado',
  observacion  text,
  orden        int,                  -- orden manual en la lista
  diffs        boolean not null default false,
  usuario      text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists idx_inv_fecha    on inventarios (fecha);
create index if not exists idx_inv_deposito on inventarios (deposito);
create index if not exists idx_inv_estado   on inventarios (estado);

-- ── Ítems / materiales de cada inventario (con conteo) ──────────────────────
create table if not exists inventario_items (
  id             bigint generated by default as identity primary key,
  inventario_id  bigint not null references inventarios(id) on delete cascade,
  codigo         text not null,
  descripcion    text,
  um             text default 'UN',
  sap            numeric,            -- cantidad que figura en SAP (col. "Libre utilización")
  contado        numeric,            -- cantidad contada
  diff           numeric,            -- contado - sap (null si sin datos)
  motivo         text,               -- averiado, vencido, etc. (si hay diferencia)
  nota           text,
  valor          numeric,            -- valor SAP del stock (col. "Valor libre util.")
  centro         text,               -- centro SAP (col. "Centro")
  almacen        text,               -- almacén SAP (col. "Almacén")
  created_at     timestamptz not null default now()
);
-- Si la tabla ya existía, agregar las columnas nuevas (idempotente):
alter table inventario_items add column if not exists valor   numeric;
alter table inventario_items add column if not exists centro  text;
alter table inventario_items add column if not exists almacen text;
create index if not exists idx_invitems_inv on inventario_items (inventario_id);

-- ── updated_at automático en inventarios ───────────────────────────────────
create or replace function inventarios_touch()
returns trigger language plpgsql as $$
begin new.updated_at := now(); return new; end $$;
drop trigger if exists trg_inventarios_touch on inventarios;
create trigger trg_inventarios_touch before update on inventarios
  for each row execute function inventarios_touch();

-- ── RLS: lectura/escritura anon (control fino = SSO en la UI) ───────────────
alter table inventarios      enable row level security;
alter table inventario_items enable row level security;
drop policy if exists anon_all on inventarios;
drop policy if exists anon_all on inventario_items;
create policy anon_all on inventarios      for all to anon using (true) with check (true);
create policy anon_all on inventario_items for all to anon using (true) with check (true);

grant usage on schema public to anon, authenticated;
grant all on inventarios      to anon, authenticated;
grant all on inventario_items to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;

-- (Opcional) Realtime
do $$
begin
  begin alter publication supabase_realtime add table inventarios; exception when others then null; end;
  begin alter publication supabase_realtime add table inventario_items; exception when others then null; end;
end $$;
